# syntax=docker/dockerfile:1.10.0
FROM ruby:3.4.5

# Setup the buildkite-agent user/group
RUN groupadd -r buildkite-agent && \
      useradd -u 9999 -r -g buildkite-agent buildkite-agent && \
      mkdir -p /home/buildkite-agent

# Setup the work directory where the application will live
ENV APP_HOME /var/www
WORKDIR $APP_HOME

# Setup bundler options to install gems in the work directory
RUN gem install bundler && \
      bundle config --local app_config /usr/local/bundle/config && \
      bundle config --local path vendor/bundle && \
      mkdir /home/buildkite-agent/.gem # This is needed for publishing gems from inside your container

# RAILS APP: Add Gemfile and Gemfile.lock to the work directory
COPY Gemfile* $APP_HOME/

# LIBRARY: Add Gemfile, Gemfile.lock, and gemspec to the work directory
COPY Gemfile* deprecation_helper.gemspec $APP_HOME/

# Run bundle install with minimal dependencies
RUN --mount=type=secret,id=cloudsmith_api_key,env=CLOUDSMITH_API_KEY \
      BUNDLE_DL__CLOUDSMITH__IO="token:${CLOUDSMITH_API_KEY}" \
      bundle install

# Add the rest of the source, now that dependencies are installed
COPY . $APP_HOME

# Change the owner of the relevant directories to the buildkite-agent
RUN chown -R buildkite-agent:buildkite-agent /home/buildkite-agent && \
      chown -R buildkite-agent:buildkite-agent $APP_HOME && \
      chown -R buildkite-agent:buildkite-agent /usr/local/bundle/config

# Setup the container to run as the buildkite-agent user
USER buildkite-agent
