steps:
  - name: ':rspec: RSpec'
    command: test.sh
    timeout_in_minutes: 10
    env:
      BUILDKITE_DOCKER: 'true'
      BUILDKITE_DOCKER_FILE: 'Dockerfile.test'
  - wait
  - block: ':rocket: Publish to Gem Server?'
  - name: ':ruby: Publish to Rubygems'
    agents:
      queue: gemstash-publish
    command: gem build deprecation_helper.gemspec && .buildkite/store_rubygems_key.sh &&  gem push --key rubygems *.gem
