steps:
  - name: ':docker: Build test image'
    key: build
    plugins:
      - ssh://git@github.com/Gusto/cloudsmith-auth-buildkite-plugin.git#v2.2.0: ~
      - docker-compose#v5.4.1:
          build: app
          config: .buildkite/docker-compose.yml
          env:
            - BUNDLE_DL__CLOUDSMITH__IO
            - CLOUDSMITH_API_KEY
    timeout_in_minutes: 10

  - wait

  - name: ':rspec: RSpec'
    command: test.sh
    timeout_in_minutes: 10
    depends_on: build
    plugins:
      - ssh://git@github.com/Gusto/cloudsmith-auth-buildkite-plugin.git#v2.2.0: ~
      - docker-compose#v5.4.1:
          run: app
          config: .buildkite/docker-compose.yml
          env:
            - BUNDLE_DL__CLOUDSMITH__IO
            - CLOUDSMITH_API_KEY

  - name: ':sorbet: Sorbet typecheck'
    command: typecheck.sh
    timeout_in_minutes: 10
    depends_on: build
    plugins:
      - ssh://git@github.com/Gusto/cloudsmith-auth-buildkite-plugin.git#v2.2.0: ~
      - docker-compose#v5.4.1:
          run: app
          config: .buildkite/docker-compose.yml
          env:
            - BUNDLE_DL__CLOUDSMITH__IO
            - CLOUDSMITH_API_KEY

  - wait

  - block: ':rocket: Publish to Gem Server?'
    branches: main

  - name: ':ruby: Publish to Rubygems'
    branches: main
    agents:
      queue: gemstash-publish
    command: gem build deprecation_helper.gemspec && .buildkite/store_rubygems_key.sh &&  gem push --key rubygems *.gem
