steps:
  - name: ':rspec: RSpec'
    command: test.sh
    timeout_in_minutes: 10
    env:
      BUILDKITE_DOCKER: 'true'
      BUILDKITE_DOCKER_FILE: 'Dockerfile.test'
  - wait
  - block: ':rocket: Publish to Gem Server?'
    branches: main
  - name: ':ruby: Publish'
    branches: main
    agents:
      queue: gemstash-publish
    command: gem build deprecation_helper.gemspec && gem push --key gemstash --host https://gemstash.zp-int.com/private *.gem
    plugins:
      - docker-compose#v3.5.0:
          config: '.buildkite/docker-compose.yml'
          run: 'app'
